# Конфигурационный файл для программы пакетного сведения документов PDF и DOCX
# (Этот файл должен называться "mix_config.yml")

#       == Каталоги с исходными файлами ==

# Каталог, в котором искать файлы .docx
docx_src_dir: C:/Users/Olduser/Downloads

# Каталог, в котором искать файлы .pdf (сканированные версии)
pdf_src_dir: C:/Users/Olduser/Downloads


#       == Каталоги, создаваемые на диске автоматически ==
#   Примеры:
#    - полный путь:                           C:/Users/User/Documents
#    - полный путь (с диском по умолчанию):   /Temp/docxpdf  (будет создан C:\Temp\docxpdf)
#    - относительный путь (не рекомендуется): work/result    (каталог будет создан в каталоге с программой)

# Каталог, в который будут сохранены текстовые файлы отчёта
log_dir: work

# Каталог для временного хранения документов, сконвертированных их DOCX в PDF
# (Необходимо очистить, если исходные DOCX были обновлены, иначе подтянутся старые версии!)
temp_dir: /Temp/docxpdf

# Каталог, в который будут сохранены готовые (сведённые) файлы PDF
result_dir: work/final


#       == Параметры обработки документов ==

# сколько страниц взять из PDF (1 и больше), остально е будет взято из DOCX
get_pages_from_pdf: 3

# Выравнивание по концу документа:
# ориентироваться на файл PDF, если размеры документов отличаются    (true)
# иначе, игнорировать размеры - всегда считать от начала документа  (false)
smart_solution_on_different_sizes: true

# останавливать работу при любой ошибке (true / false)
stop_on_error: true
