# Конфигурационный файл программы пакетного сведения документов PDF и DOCX

# Каталог, в котором искать файлы .docx
docx_src_dir: C:/Users/Olduser/Downloads

# Каталог, в котором искать файлы .pdf (сканированные версии)
pdf_src_dir: C:/Users/Olduser/Downloads



# Каталог, в который будут сохранены текстовые файлы отчёта
log_dir: work

# Каталог для временного хранения документов, сконвертированных их DOCX в PDF
# (Необходимо очистить, если исходные DOCX были обновлены!)
temp_dir: work/temp

# Каталог, в который будут сохранены готовые файлы PDF
result_dir: work/final



# сколько страниц взять из PDF (1 и больше), остально е будет взято из DOCX
get_pages_from_pdf: 3

# ориентироваться на файл PDF, если размеры документов отличаются (true / false)
smart_solution_on_different_sizes: true

# останавливать работу при любой ошибке (true / false)
stop_on_error: true
